"""Create all FillTheWord tables

Revision ID: 2a3b4c5d6e7f
Revises: 22e841f3849e
Create Date: 2025-12-12 04:56:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3b4c5d6e7f'
down_revision: Union[str, None] = '22e841f3849e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create languages table
    op.create_table('language',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('voice_model', sa.String(length=100), nullable=True),
    sa.Column('voice_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_id'), 'language', ['id'], unique=False)
    op.create_index(op.f('ix_language_code'), 'language', ['code'], unique=True)

    # Create words table
    op.create_table('word',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lemma', sa.String(length=200), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.Column('pronunciation', sa.String(length=500), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_id'), 'word', ['id'], unique=False)

    # Create decks table
    op.create_table('deck',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_id'), 'deck', ['id'], unique=False)

    # Create sentences table
    op.create_table('sentence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('translation', sa.String(length=1000), nullable=False),
    sa.Column('word_id', sa.String(length=36), nullable=False),
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('gap_start', sa.Integer(), nullable=False),
    sa.Column('gap_end', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_id'), 'sentence', ['id'], unique=False)

    # Create cards table
    op.create_table('card',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sentence_id', sa.String(length=36), nullable=False),
    sa.Column('deck_id', sa.String(length=36), nullable=False),
    sa.Column('grammar_hint', sa.String(length=500), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('gap_start', sa.Integer(), nullable=True),
    sa.Column('gap_end', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_id'), 'card', ['id'], unique=False)

    # Create users table
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('native_language', sa.String(length=10), nullable=True),
    sa.Column('target_language', sa.String(length=10), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=True),
    sa.Column('daily_new_limit', sa.Integer(), nullable=True),
    sa.Column('easiness_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)

    # Create user_card_states table
    op.create_table('usercardstate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('easiness_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('correct_reviews', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usercardstate_id'), 'usercardstate', ['id'], unique=False)

    # Create review_events table
    op.create_table('reviewevent',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('user_answer', sa.String(length=200), nullable=True),
    sa.Column('correct_answer', sa.String(length=200), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=True),
    sa.Column('previous_easiness', sa.Float(), nullable=True),
    sa.Column('new_easiness', sa.Float(), nullable=True),
    sa.Column('previous_interval', sa.Integer(), nullable=True),
    sa.Column('new_interval', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewevent_id'), 'reviewevent', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewevent')
    op.drop_table('usercardstate')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_card_id'), table_name='card')
    op.drop_table('card')
    op.drop_index(op.f('ix_sentence_id'), table_name='sentence')
    op.drop_table('sentence')
    op.drop_index(op.f('ix_deck_id'), table_name='deck')
    op.drop_table('deck')
    op.drop_index(op.f('ix_word_id'), table_name='word')
    op.drop_table('word')
    op.drop_index(op.f('ix_language_code'), table_name='language')
    op.drop_index(op.f('ix_language_id'), table_name='language')
    op.drop_table('language')
    # ### end Alembic commands ###