"""Convert String(36) columns to UUID

Revision ID: 870c67fe87be
Revises: 2a3b4c5d6e7f
Create Date: 2025-12-12 06:20:37.950277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870c67fe87be'
down_revision: Union[str, None] = '2a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign key constraints temporarily
    op.drop_constraint('word_language_id_fkey', 'word', type_='foreignkey')
    op.drop_constraint('sentence_word_id_fkey', 'sentence', type_='foreignkey')
    op.drop_constraint('sentence_language_id_fkey', 'sentence', type_='foreignkey')
    op.drop_constraint('deck_language_id_fkey', 'deck', type_='foreignkey')
    op.drop_constraint('card_sentence_id_fkey', 'card', type_='foreignkey')
    op.drop_constraint('card_deck_id_fkey', 'card', type_='foreignkey')
    op.drop_constraint('usercardstate_user_id_fkey', 'usercardstate', type_='foreignkey')
    op.drop_constraint('usercardstate_card_id_fkey', 'usercardstate', type_='foreignkey')
    op.drop_constraint('reviewevent_user_id_fkey', 'reviewevent', type_='foreignkey')
    op.drop_constraint('reviewevent_card_id_fkey', 'reviewevent', type_='foreignkey')

    # Convert primary key columns from varchar to uuid
    op.execute("ALTER TABLE language ALTER COLUMN id TYPE UUID USING id::uuid")
    op.execute("ALTER TABLE word ALTER COLUMN id TYPE UUID USING id::uuid")
    op.execute("ALTER TABLE sentence ALTER COLUMN id TYPE UUID USING id::uuid")
    op.execute("ALTER TABLE deck ALTER COLUMN id TYPE UUID USING id::uuid")
    op.execute("ALTER TABLE card ALTER COLUMN id TYPE UUID USING id::uuid")
    op.execute("ALTER TABLE \"user\" ALTER COLUMN id TYPE UUID USING id::uuid")
    op.execute("ALTER TABLE usercardstate ALTER COLUMN id TYPE UUID USING id::uuid")
    op.execute("ALTER TABLE reviewevent ALTER COLUMN id TYPE UUID USING id::uuid")

    # Convert foreign key columns from varchar to uuid
    op.execute("ALTER TABLE word ALTER COLUMN language_id TYPE UUID USING language_id::uuid")
    op.execute("ALTER TABLE sentence ALTER COLUMN word_id TYPE UUID USING word_id::uuid")
    op.execute("ALTER TABLE sentence ALTER COLUMN language_id TYPE UUID USING language_id::uuid")
    op.execute("ALTER TABLE deck ALTER COLUMN language_id TYPE UUID USING language_id::uuid")
    op.execute("ALTER TABLE card ALTER COLUMN sentence_id TYPE UUID USING sentence_id::uuid")
    op.execute("ALTER TABLE card ALTER COLUMN deck_id TYPE UUID USING deck_id::uuid")
    op.execute("ALTER TABLE usercardstate ALTER COLUMN user_id TYPE UUID USING user_id::uuid")
    op.execute("ALTER TABLE usercardstate ALTER COLUMN card_id TYPE UUID USING card_id::uuid")
    op.execute("ALTER TABLE reviewevent ALTER COLUMN user_id TYPE UUID USING user_id::uuid")
    op.execute("ALTER TABLE reviewevent ALTER COLUMN card_id TYPE UUID USING card_id::uuid")
    op.execute("ALTER TABLE reviewevent ALTER COLUMN session_id TYPE UUID USING session_id::uuid")

    # Recreate foreign key constraints with UUID types
    op.create_foreign_key('word_language_id_fkey', 'word', 'language', ['language_id'], ['id'])
    op.create_foreign_key('sentence_word_id_fkey', 'sentence', 'word', ['word_id'], ['id'])
    op.create_foreign_key('sentence_language_id_fkey', 'sentence', 'language', ['language_id'], ['id'])
    op.create_foreign_key('deck_language_id_fkey', 'deck', 'language', ['language_id'], ['id'])
    op.create_foreign_key('card_sentence_id_fkey', 'card', 'sentence', ['sentence_id'], ['id'])
    op.create_foreign_key('card_deck_id_fkey', 'card', 'deck', ['deck_id'], ['id'])
    op.create_foreign_key('usercardstate_user_id_fkey', 'usercardstate', 'user', ['user_id'], ['id'])
    op.create_foreign_key('usercardstate_card_id_fkey', 'usercardstate', 'card', ['card_id'], ['id'])
    op.create_foreign_key('reviewevent_user_id_fkey', 'reviewevent', 'user', ['user_id'], ['id'])
    op.create_foreign_key('reviewevent_card_id_fkey', 'reviewevent', 'card', ['card_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Convert foreign key columns from uuid back to varchar
    op.execute("ALTER TABLE reviewevent ALTER COLUMN session_id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE reviewevent ALTER COLUMN card_id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE reviewevent ALTER COLUMN user_id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE usercardstate ALTER COLUMN card_id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE usercardstate ALTER COLUMN user_id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE card ALTER COLUMN deck_id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE card ALTER COLUMN sentence_id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE deck ALTER COLUMN language_id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE sentence ALTER COLUMN language_id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE sentence ALTER COLUMN word_id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE word ALTER COLUMN language_id TYPE VARCHAR(36)")

    # Convert primary key columns from uuid back to varchar
    op.execute("ALTER TABLE reviewevent ALTER COLUMN id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE usercardstate ALTER COLUMN id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE \"user\" ALTER COLUMN id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE card ALTER COLUMN id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE deck ALTER COLUMN id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE sentence ALTER COLUMN id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE word ALTER COLUMN id TYPE VARCHAR(36)")
    op.execute("ALTER TABLE language ALTER COLUMN id TYPE VARCHAR(36)")

    # ### end Alembic commands ###
