"""Add updated_at to reviewevent

Revision ID: 97266a26470a
Revises: fix_user_language_cols
Create Date: 2025-12-12 12:48:51.127117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97266a26470a'
down_revision: Union[str, None] = 'fix_user_language_cols'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create memorystage enum first (if not exists)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE memorystage AS ENUM ('NEW', 'LEARNING', 'REVIEW', 'RELEARN', 'MATURE');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'grammar_hint',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('card', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('card', 'gap_start',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('card', 'gap_end',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('card', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('deck', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('deck', 'difficulty_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deck', 'card_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deck', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('language', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('language', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('language', 'voice_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('language', 'voice_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('language', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('reviewevent', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('reviewevent', 'quality',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviewevent', 'response_time_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviewevent', 'user_answer',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('reviewevent', 'correct_answer',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('reviewevent', 'was_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('reviewevent', 'hints_used',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sentence', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('sentence', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user', 'language_preference',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=2),
               nullable=False)
    op.alter_column('user', 'daily_new_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'easiness_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    op.alter_column('usercardstate', 'repetitions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardstate', 'easiness_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('usercardstate', 'interval_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardstate', 'next_review_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('usercardstate', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('NEW', 'LEARNING', 'REVIEW', 'RELEARN', 'MATURE', name='memorystage'),
               nullable=False,
               postgresql_using='status::text::memorystage')
    op.alter_column('usercardstate', 'total_reviews',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardstate', 'correct_reviews',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('word', 'lemma',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('word', 'text',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('word', 'part_of_speech',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('word', 'pronunciation',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('word', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_word_lemma'), 'word', ['lemma'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_lemma'), table_name='word')
    op.alter_column('word', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('word', 'pronunciation',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('word', 'part_of_speech',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('word', 'text',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('word', 'lemma',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('usercardstate', 'correct_reviews',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercardstate', 'total_reviews',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercardstate', 'status',
               existing_type=sa.Enum('NEW', 'LEARNING', 'REVIEW', 'RELEARN', 'MATURE', name='memorystage'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('usercardstate', 'next_review_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('usercardstate', 'interval_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercardstate', 'easiness_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('usercardstate', 'repetitions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'easiness_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user', 'daily_new_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'language_preference',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('sentence', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sentence', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('reviewevent', 'hints_used',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviewevent', 'was_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('reviewevent', 'correct_answer',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('reviewevent', 'user_answer',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('reviewevent', 'response_time_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviewevent', 'quality',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('reviewevent', 'updated_at')
    op.alter_column('language', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('language', 'voice_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('language', 'voice_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('language', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('language', 'code',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('deck', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('deck', 'card_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deck', 'difficulty_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deck', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('card', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('card', 'gap_end',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('card', 'gap_start',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('card', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('card', 'grammar_hint',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
