"""Add Spec4 models: sentence variety, frequency progression, session stats

Revision ID: add_spec4_models
Revises: add_language_to_word_frequency

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_spec4_models'
down_revision = 'add_language_to_word_frequency'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum type for source_type
    sourcetype_enum = postgresql.ENUM('CORPUS', 'GENERATED', 'MANUAL', name='sourcetype')
    sourcetype_enum.create(op.get_bind())

    # Add new columns to Sentence model
    op.add_column('sentence', sa.Column('source_type', sa.Enum('CORPUS', 'GENERATED', 'MANUAL', name='sourcetype'), nullable=True))
    op.add_column('sentence', sa.Column('grammar_hint', sa.String(length=100), nullable=True))
    op.alter_column('sentence', 'translation', nullable=True)

    # Set default values for existing records
    op.execute("UPDATE sentence SET source_type = 'MANUAL' WHERE source_type IS NULL")
    op.execute("UPDATE sentence SET grammar_hint = word.part_of_speech FROM word WHERE sentence.word_id = word.id AND grammar_hint IS NULL")

    # Now make the column NOT NULL
    op.alter_column('sentence', 'source_type', nullable=False)

    # Add sentence_id to ReviewEvent
    op.add_column('reviewevent', sa.Column('sentence_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_reviewevent_sentence', 'reviewevent', 'sentence', ['sentence_id'], ['id'])

    # Add word_goal_rank to User model
    op.add_column('user', sa.Column('word_goal_rank', sa.Integer(), nullable=False, server_default='1000'))

    # Create word_sentence table
    op.create_table('word_sentence',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('word_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('sentence_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('is_primary', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['sentence_id'], ['sentence.id'], ),
        sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_sentence_word_id'), 'word_sentence', ['word_id'], unique=False)
    op.create_index(op.f('ix_word_sentence_sentence_id'), 'word_sentence', ['sentence_id'], unique=False)

    # Create user_frequency_progress table
    op.create_table('user_frequency_progress',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('word_goal_rank', sa.Integer(), nullable=False),
        sa.Column('current_window_end_rank', sa.Integer(), nullable=False),
        sa.Column('max_contiguous_mastered_rank', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_frequency_progress_user_id'), 'user_frequency_progress', ['user_id'], unique=False)

    # Create user_session_stats table
    op.create_table('user_session_stats',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('cards_shown', sa.Integer(), nullable=False),
        sa.Column('new_cards_shown', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'date')
    )
    op.create_index(op.f('ix_user_session_stats_user_id'), 'user_session_stats', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop tables
    op.drop_index(op.f('ix_user_session_stats_user_id'), table_name='user_session_stats')
    op.drop_table('user_session_stats')
    op.drop_index(op.f('ix_user_frequency_progress_user_id'), table_name='user_frequency_progress')
    op.drop_table('user_frequency_progress')
    op.drop_index(op.f('ix_word_sentence_sentence_id'), table_name='word_sentence')
    op.drop_index(op.f('ix_word_sentence_word_id'), table_name='word_sentence')
    op.drop_table('word_sentence')

    # Remove columns
    op.drop_column('user', 'word_goal_rank')
    op.drop_constraint('fk_reviewevent_sentence', table_name='reviewevent', type_='foreignkey')
    op.drop_column('reviewevent', 'sentence_id')
    op.drop_column('sentence', 'grammar_hint')
    op.drop_column('sentence', 'source_type')
    op.alter_column('sentence', 'translation', nullable=False)

    # ### end Alembic commands ###