"""Add language_code column to word_frequencies table

Revision ID: add_language_to_word_frequency
Revises: 001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'add_language_to_word_frequency'
down_revision: Union[str, None] = 'b05058818b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add language_code column to word_frequencies table
    op.add_column('word_frequencies', sa.Column('language_code', sa.String(length=10), server_default='en', nullable=False, comment='Language code (en, fr, etc.)'))

    # Update existing records to 'en' since they are English words
    op.execute(
        "UPDATE word_frequencies SET language_code = 'en' WHERE language_code IS NULL"
    )

    # Create composite indexes for performance
    # Index for language + word lookup
    op.create_index(
        'idx_word_frequency_lang_word',
        'word_frequencies',
        ['language_code', 'word'],
        unique=False,
        postgresql_using='btree'
    )

    # Index for language + rank lookup
    op.create_index(
        'idx_word_frequency_lang_rank',
        'word_frequencies',
        ['language_code', 'rank'],
        unique=False,
        postgresql_using='btree'
    )


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###

    # Drop composite indexes
    op.drop_index('idx_word_frequency_lang_rank', table_name='word_frequencies')
    op.drop_index('idx_word_frequency_lang_word', table_name='word_frequencies')

    # Set language_code to NULL temporarily before dropping column
    op.execute("UPDATE word_frequencies SET language_code = NULL")

    # Drop language_code column
    op.drop_column('word_frequencies', 'language_code')