"""Add analytics models and coverage_pct

Revision ID: b05058818b1a
Revises: 879146c0ff2b
Create Date: 2025-12-13 03:12:12.680115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b05058818b1a'
down_revision: Union[str, None] = '879146c0ff2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create MemoryStage enum type first
    op.execute("CREATE TYPE memorystage AS ENUM ('NEW', 'LEARNING', 'REVIEW', 'RELEARN', 'MATURE')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_themes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Theme name (ex: Daily actions, Travel)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the theme'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether this theme is active'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_word_theme_active', 'word_themes', ['is_active'], unique=False)
    op.create_index('idx_word_theme_name', 'word_themes', ['name'], unique=False)
    op.create_table('user_daily_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('date', sa.Date(), nullable=False, comment='Statistics date'),
    sa.Column('cards_answered', sa.Integer(), nullable=False, comment='Number of cards answered'),
    sa.Column('new_words_learned', sa.Integer(), nullable=False, comment='New words that passed mastery threshold'),
    sa.Column('reviews_done', sa.Integer(), nullable=False, comment='Number of review attempts'),
    sa.Column('accuracy', sa.Float(), nullable=False, comment='Daily accuracy rate'),
    sa.Column('cumulative_mastered_words', sa.Integer(), nullable=False, comment='Total mastered words up to this date'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_daily_stats_accuracy', 'user_daily_stats', ['accuracy'], unique=False)
    op.create_index('idx_user_daily_stats_cards_answered', 'user_daily_stats', ['cards_answered'], unique=False)
    op.create_index('idx_user_daily_stats_cumulative_mastered', 'user_daily_stats', ['cumulative_mastered_words'], unique=False)
    op.create_index('idx_user_daily_stats_date', 'user_daily_stats', ['date'], unique=False)
    op.create_index('idx_user_daily_stats_user', 'user_daily_stats', ['user_id'], unique=False)
    op.create_index('idx_user_daily_stats_user_date', 'user_daily_stats', ['user_id', 'date'], unique=True)
    op.create_table('user_theme_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('theme_id', sa.UUID(), nullable=False, comment='Theme ID'),
    sa.Column('attempts', sa.Integer(), nullable=False, comment='Total number of attempts'),
    sa.Column('correct', sa.Integer(), nullable=False, comment='Number of correct attempts'),
    sa.Column('accuracy', sa.Float(), nullable=False, comment='Accuracy rate (correct / attempts)'),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=False, comment='Average response time in milliseconds'),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=True, comment='Last practice timestamp'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Update timestamp'),
    sa.ForeignKeyConstraint(['theme_id'], ['word_themes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_theme_stats_accuracy', 'user_theme_stats', ['accuracy'], unique=False)
    op.create_index('idx_user_theme_stats_last_practiced', 'user_theme_stats', ['last_practiced_at'], unique=False)
    op.create_index('idx_user_theme_stats_theme', 'user_theme_stats', ['theme_id'], unique=False)
    op.create_index('idx_user_theme_stats_user', 'user_theme_stats', ['user_id'], unique=False)
    op.create_index('idx_user_theme_stats_user_theme', 'user_theme_stats', ['user_id', 'theme_id'], unique=True)
    op.create_table('word_theme_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False, comment='Word ID'),
    sa.Column('theme_id', sa.UUID(), nullable=False, comment='Theme ID'),
    sa.Column('weight', sa.Float(), nullable=True, comment='Weight for multiple themes per word (0..1)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether this mapping is active'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Update timestamp'),
    sa.ForeignKeyConstraint(['theme_id'], ['word_themes.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_word_theme_mapping_active', 'word_theme_mappings', ['is_active'], unique=False)
    op.create_index('idx_word_theme_mapping_theme', 'word_theme_mappings', ['theme_id'], unique=False)
    op.create_index('idx_word_theme_mapping_word', 'word_theme_mappings', ['word_id'], unique=False)
    op.create_index('idx_word_theme_mapping_word_theme', 'word_theme_mappings', ['word_id', 'theme_id'], unique=True)
    op.alter_column('card', 'grammar_hint',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('card', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('card', 'gap_start',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('card', 'gap_end',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('card', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('deck', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('deck', 'difficulty_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deck', 'card_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deck', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('language', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('language', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('language', 'voice_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('language', 'voice_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('language', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('reviewevent', 'quality',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviewevent', 'response_time_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviewevent', 'user_answer',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('reviewevent', 'correct_answer',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('reviewevent', 'was_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('reviewevent', 'hints_used',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviewevent', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sentence', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('sentence', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user', 'language_preference',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=2),
               nullable=False)
    op.alter_column('user', 'daily_new_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'easiness_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    op.alter_column('user_word_stats', 'mastery_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0.0 = new, 1.0 = mastered',
               existing_nullable=False)
    op.alter_column('user_word_stats', 'last_result',
               existing_type=sa.BOOLEAN(),
               comment='Result of last attempt',
               existing_nullable=True)
    op.alter_column('user_word_stats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_word_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('usercardstate', 'repetitions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardstate', 'easiness_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('usercardstate', 'interval_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardstate', 'next_review_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.execute("ALTER TABLE usercardstate ALTER COLUMN status TYPE memorystage USING status::memorystage")
    op.alter_column('usercardstate', 'total_reviews',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardstate', 'correct_reviews',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('word', 'lemma',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('word', 'text',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('word', 'part_of_speech',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('word', 'pronunciation',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('word', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_word_lemma'), 'word', ['lemma'], unique=False)
    op.add_column('word_frequencies', sa.Column('coverage_pct', sa.Float(), nullable=True, comment='Cumulative coverage percentage (0-100)'))
    op.alter_column('word_frequencies', 'word',
               existing_type=sa.VARCHAR(length=100),
               comment='Lowercase word',
               existing_nullable=False)
    op.alter_column('word_frequencies', 'rank',
               existing_type=sa.INTEGER(),
               comment='Frequency rank (1=most frequent)',
               existing_nullable=False)
    op.alter_column('word_frequencies', 'frequency_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Normalized frequency score',
               existing_nullable=True)
    op.alter_column('word_frequencies', 'band',
               existing_type=sa.INTEGER(),
               comment='Frequency band: 1(1-1000), 2(1001-3000), 3(3001-6000), 4(6001-10000)',
               existing_nullable=False)
    op.alter_column('word_frequencies', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether this word is available for selection',
               existing_nullable=True)
    op.alter_column('word_frequencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('word_frequencies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word_frequencies', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('word_frequencies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('word_frequencies', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this word is available for selection',
               existing_nullable=True)
    op.alter_column('word_frequencies', 'band',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Frequency band: 1(1-1000), 2(1001-3000), 3(3001-6000), 4(6001-10000)',
               existing_nullable=False)
    op.alter_column('word_frequencies', 'frequency_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Normalized frequency score',
               existing_nullable=True)
    op.alter_column('word_frequencies', 'rank',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Frequency rank (1=most frequent)',
               existing_nullable=False)
    op.alter_column('word_frequencies', 'word',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Lowercase word',
               existing_nullable=False)
    op.drop_column('word_frequencies', 'coverage_pct')
    op.drop_index(op.f('ix_word_lemma'), table_name='word')
    op.alter_column('word', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('word', 'pronunciation',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('word', 'part_of_speech',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('word', 'text',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('word', 'lemma',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('usercardstate', 'correct_reviews',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercardstate', 'total_reviews',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.execute("ALTER TABLE usercardstate ALTER COLUMN status TYPE VARCHAR(20) USING status::text")
    op.alter_column('usercardstate', 'next_review_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('usercardstate', 'interval_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercardstate', 'easiness_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('usercardstate', 'repetitions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_word_stats', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_word_stats', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_word_stats', 'last_result',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Result of last attempt',
               existing_nullable=True)
    op.alter_column('user_word_stats', 'mastery_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='0.0 = new, 1.0 = mastered',
               existing_nullable=False)
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'easiness_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user', 'daily_new_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'language_preference',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('sentence', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sentence', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('reviewevent', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('reviewevent', 'hints_used',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviewevent', 'was_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('reviewevent', 'correct_answer',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('reviewevent', 'user_answer',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('reviewevent', 'response_time_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviewevent', 'quality',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('language', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('language', 'voice_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('language', 'voice_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('language', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('language', 'code',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('deck', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('deck', 'card_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deck', 'difficulty_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deck', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('card', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('card', 'gap_end',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('card', 'gap_start',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('card', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('card', 'grammar_hint',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_index('idx_word_theme_mapping_word_theme', table_name='word_theme_mappings')
    op.drop_index('idx_word_theme_mapping_word', table_name='word_theme_mappings')
    op.drop_index('idx_word_theme_mapping_theme', table_name='word_theme_mappings')
    op.drop_index('idx_word_theme_mapping_active', table_name='word_theme_mappings')
    op.drop_table('word_theme_mappings')
    op.drop_index('idx_user_theme_stats_user_theme', table_name='user_theme_stats')
    op.drop_index('idx_user_theme_stats_user', table_name='user_theme_stats')
    op.drop_index('idx_user_theme_stats_theme', table_name='user_theme_stats')
    op.drop_index('idx_user_theme_stats_last_practiced', table_name='user_theme_stats')
    op.drop_index('idx_user_theme_stats_accuracy', table_name='user_theme_stats')
    op.drop_table('user_theme_stats')
    op.drop_index('idx_user_daily_stats_user_date', table_name='user_daily_stats')
    op.drop_index('idx_user_daily_stats_user', table_name='user_daily_stats')
    op.drop_index('idx_user_daily_stats_date', table_name='user_daily_stats')
    op.drop_index('idx_user_daily_stats_cumulative_mastered', table_name='user_daily_stats')
    op.drop_index('idx_user_daily_stats_cards_answered', table_name='user_daily_stats')
    op.drop_index('idx_user_daily_stats_accuracy', table_name='user_daily_stats')
    op.drop_table('user_daily_stats')
    op.drop_index('idx_word_theme_name', table_name='word_themes')
    op.drop_index('idx_word_theme_active', table_name='word_themes')
    op.drop_table('word_themes')

    # Drop MemoryStage enum type
    op.execute("DROP TYPE memorystage")

    # ### end Alembic commands ###
